apiVersion: v1
kind: Service
metadata:
  name: flask-test-service-fe
spec:
  selector:
    app: flask-test-app-fe
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app-fe
spec:
  selector:
    matchLabels:
      app: flask-test-app-fe
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app-fe
    spec:
      containers:
      - name: flask-test-app-fe
        image: docker-app-back-end-kube
        imagePullPolicy: Never
        ports:
        - containerPort: 3000